version: "3.8"

name: "portfolio-api"

services:
  s3:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    command:
      server /data --console-address ":9001"
    volumes:
      - s3-data:/data
  db:
    image: postgres:16.4-alpine3.20
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  s3-data:
    driver: local
  db-data:
    driver: local